const fs = require("fs");
const lines = fs.readFileSync("src/screens/AdminScreen.tsx", "utf8").split("\n");

// Find deposits tab start and end
let startIdx = -1;
let endIdx = -1;
for (let i = 0; i < lines.length; i++) {
    if (lines[i].includes('{activeTab === "deposits" && (') && startIdx === -1) {
        startIdx = i;
    }
    if (startIdx > -1 && lines[i].includes('{activeTab === "gcash" && (')) {
        endIdx = i;
        break;
    }
}
console.log("Deposits tab from line", startIdx + 1, "to", endIdx);

const newDepositsTab = [
'            {activeTab === "deposits" && (',
'              <div className="flex flex-col gap-3">',
'                <div className="flex items-center justify-between px-1 mb-2">',
'                  <p className="text-[10px] text-brand-text/40 uppercase tracking-widest font-black">{deposits.length} Deposit Requests</p>',
'                  <div className="flex gap-2">',
'                    <span className="text-[9px] bg-yellow-500/20 text-yellow-400 px-2 py-1 rounded-lg font-black">{deposits.filter((d:any) => d.status === "pending").length} Pending</span>',
'                    <span className="text-[9px] bg-green-500/20 text-green-400 px-2 py-1 rounded-lg font-black">{deposits.filter((d:any) => d.status === "approved").length} Approved</span>',
'                  </div>',
'                </div>',
'                {deposits.length === 0 ? (',
'                  <div className="text-center py-12">',
'                    <p className="text-brand-text/40 font-bold">No deposit requests yet</p>',
'                  </div>',
'                ) : deposits.map((d: any) => (',
'                  <div key={d.id} onClick={() => { setSelectedDeposit(d); setAdminNote(""); }} className="bg-brand-card/5 border border-brand-border rounded-2xl p-4 cursor-pointer hover:border-brand-primary/30 transition-all active:scale-[0.99]">',
'                    <div className="flex items-start gap-3">',
'                      {d.screenshot && <img src={d.screenshot} alt="Receipt" className="w-16 h-16 rounded-xl object-cover shrink-0 border border-brand-border" />}',
'                      <div className="flex-1 min-w-0">',
'                        <div className="flex items-start justify-between gap-2">',
'                          <div>',
'                            <p className="text-sm font-black text-brand-text">{d.userName}</p>',
'                            <p className="text-[10px] text-brand-text/40 truncate">{d.userEmail}</p>',
'                          </div>',
'                          <span className={"text-[9px] font-black px-2 py-0.5 rounded-full shrink-0 " + (d.status === "approved" ? "bg-green-500/20 text-green-400" : d.status === "rejected" ? "bg-red-500/20 text-red-400" : "bg-yellow-500/20 text-yellow-400")}>',
'                            {(d.status || "pending").toUpperCase()}',
'                          </span>',
'                        </div>',
'                        <div className="flex items-center gap-3 mt-2">',
'                          <p className="text-lg font-black text-brand-primary">₱{(d.amount || 0).toLocaleString()}</p>',
'                          <span className="text-[9px] text-brand-text/40 font-black uppercase">{d.method || "GCash"}</span>',
'                        </div>',
'                        <p className="text-[9px] text-brand-text/30 mt-1">',
'                          {d.createdAt?.toDate?.()?.toLocaleString() || "Recently"} • Ref: {d.referenceNo}',
'                        </p>',
'                      </div>',
'                    </div>',
'                  </div>',
'                ))}',
'              </div>',
'            )}',
'            {/* Deposit Detail Modal */}',
'            {selectedDeposit && (',
'              <div className="fixed inset-0 z-[300] bg-brand-black/95 backdrop-blur-xl flex flex-col overflow-y-auto">',
'                <div className="flex items-center gap-3 px-4 py-4 border-b border-brand-border sticky top-0 bg-brand-black z-10">',
'                  <button onClick={() => { setSelectedDeposit(null); setZoomImage(false); }} className="w-10 h-10 rounded-full bg-brand-card/20 border border-brand-border flex items-center justify-center">',
'                    <ChevronUp className="w-5 h-5 rotate-[-90deg]" />',
'                  </button>',
'                  <div>',
'                    <h3 className="text-base font-black text-brand-text">Deposit Request</h3>',
'                    <p className="text-[10px] text-brand-text/40">Review and process</p>',
'                  </div>',
'                </div>',
'                <div className="p-4 flex flex-col gap-4">',
'                  {/* Status Badge */}',
'                  <div className="flex justify-center">',
'                    <span className={"text-xs font-black px-4 py-2 rounded-full " + (selectedDeposit.status === "approved" ? "bg-green-500/20 text-green-400 border border-green-500/30" : selectedDeposit.status === "rejected" ? "bg-red-500/20 text-red-400 border border-red-500/30" : "bg-yellow-500/20 text-yellow-400 border border-yellow-500/30")}>',
'                      {(selectedDeposit.status || "PENDING").toUpperCase()}',
'                    </span>',
'                  </div>',
'                  {/* User Info */}',
'                  <div className="bg-brand-card/10 border border-brand-border rounded-2xl p-4">',
'                    <p className="text-[9px] font-black uppercase tracking-widest text-brand-text/40 mb-3">User Details</p>',
'                    <div className="flex flex-col gap-2">',
'                      <div className="flex justify-between"><span className="text-[10px] text-brand-text/40">Name</span><span className="text-[10px] font-black text-brand-text">{selectedDeposit.userName}</span></div>',
'                      <div className="flex justify-between"><span className="text-[10px] text-brand-text/40">Email</span><span className="text-[10px] font-black text-brand-text">{selectedDeposit.userEmail}</span></div>',
'                      <div className="flex justify-between"><span className="text-[10px] text-brand-text/40">User ID</span><span className="text-[9px] font-mono text-brand-text/60">{selectedDeposit.userId}</span></div>',
'                    </div>',
'                  </div>',
'                  {/* Deposit Info */}',
'                  <div className="bg-brand-card/10 border border-brand-border rounded-2xl p-4">',
'                    <p className="text-[9px] font-black uppercase tracking-widest text-brand-text/40 mb-3">Deposit Details</p>',
'                    <div className="flex flex-col gap-2">',
'                      <div className="flex justify-between"><span className="text-[10px] text-brand-text/40">Amount</span><span className="text-base font-black text-brand-primary">₱{(selectedDeposit.amount || 0).toLocaleString("en-US", { minimumFractionDigits: 2 })}</span></div>',
'                      <div className="flex justify-between"><span className="text-[10px] text-brand-text/40">Method</span><span className="text-[10px] font-black text-brand-text">{selectedDeposit.method || "GCash"}</span></div>',
'                      <div className="flex justify-between"><span className="text-[10px] text-brand-text/40">Reference No</span><span className="text-[10px] font-mono font-black text-brand-text">{selectedDeposit.referenceNo}</span></div>',
'                      <div className="flex justify-between"><span className="text-[10px] text-brand-text/40">Date</span><span className="text-[10px] font-black text-brand-text">{selectedDeposit.createdAt?.toDate?.()?.toLocaleString() || "N/A"}</span></div>',
'                    </div>',
'                  </div>',
'                  {/* Proof of Payment */}',
'                  {selectedDeposit.screenshot && (',
'                    <div className="bg-brand-card/10 border border-brand-border rounded-2xl p-4">',
'                      <div className="flex items-center justify-between mb-3">',
'                        <p className="text-[9px] font-black uppercase tracking-widest text-brand-text/40">Proof of Payment</p>',
'                        <button onClick={() => setZoomImage(!zoomImage)} className="text-[9px] font-black text-brand-primary border border-brand-primary/30 px-2 py-1 rounded-lg">',
'                          {zoomImage ? "Zoom Out" : "Zoom In"}',
'                        </button>',
'                      </div>',
'                      <img src={selectedDeposit.screenshot} alt="Proof" className={"w-full rounded-xl object-contain transition-all " + (zoomImage ? "max-h-none" : "max-h-64")} />',
'                    </div>',
'                  )}',
'                  {/* Admin Note */}',
'                  {selectedDeposit.status === "pending" && (',
'                    <div>',
'                      <label className="text-[9px] font-black uppercase tracking-widest text-brand-text/40 mb-2 block">Admin Note (Optional)</label>',
'                      <textarea value={adminNote} onChange={e => setAdminNote(e.target.value)} rows={3}',
'                        className="w-full bg-brand-card/20 border border-brand-border rounded-2xl py-3 px-4 text-brand-text text-sm focus:outline-none focus:border-brand-primary/50 resize-none"',
'                        placeholder="Add a note for this deposit..." />',
'                    </div>',
'                  )}',
'                  {/* Actions */}',
'                  {selectedDeposit.status === "pending" ? (',
'                    <div className="flex gap-3 pb-8">',
'                      <button onClick={() => handleRejectDeposit(selectedDeposit)} disabled={processingDeposit}',
'                        className="flex-1 py-4 bg-red-500/10 border border-red-500/20 text-red-400 font-black uppercase tracking-widest text-sm rounded-2xl active:scale-95 transition-all disabled:opacity-50">',
'                        {processingDeposit ? "Processing..." : "Reject"}',
'                      </button>',
'                      <button onClick={() => handleApproveDeposit(selectedDeposit)} disabled={processingDeposit}',
'                        className="flex-1 py-4 bg-green-500 text-white font-black uppercase tracking-widest text-sm rounded-2xl active:scale-95 transition-all disabled:opacity-50">',
'                        {processingDeposit ? "Processing..." : "Approve ₱" + (selectedDeposit.amount || 0).toLocaleString()}',
'                      </button>',
'                    </div>',
'                  ) : (',
'                    <div className="pb-8 text-center">',
'                      <p className="text-brand-text/40 text-sm font-bold">This request has been {selectedDeposit.status}.</p>',
'                      {selectedDeposit.adminNote && <p className="text-[10px] text-brand-text/30 mt-1">Note: {selectedDeposit.adminNote}</p>}',
'                    </div>',
'                  )}',
'                </div>',
'              </div>',
'            )}',
];

lines.splice(startIdx, endIdx - startIdx, ...newDepositsTab);
fs.writeFileSync("src/screens/AdminScreen.tsx", lines.join("\n"), "utf8");
console.log("Done! Replaced deposits tab from line", startIdx + 1);
